# Generated by Django 4.1.7 on 2023-08-08 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_postreaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
